name: sim_aloha_data
task_type: single_dataset
task_modes: []

shape_meta:
  image_resolution: 128
  action:
    shape:
    - 10
  obs:
    camera_0_color:
      shape:
      - 3 # C
      - 128 # H
      - 128 # W
      type: rgb

dataset:
  _target_: unified_video_action.dataset.sim_aloha_dataset.SimAlohaDataset
  language_emb_model: null
  normalizer_type: all
  dataset_dir: data/sim_aloha/transfer_cube_0301
  horizon: 32
  aug_mode: none
  skip_frame: 1
  pad_after: 7
  pad_before: 1
  rotation_rep: rotation_6d
  seed: 42
  skip_idx: 1
  use_cache: true
  resolution: 128
  obs_keys: [camera_0_color]
  shape_meta: ${task.shape_meta}
  goal_sample: intermediate
